---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: drupal
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: drupal
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: drupal
    version: 5.0.0
  values:
    ingress:
      enabled: true
      hosts:
        - name: fluxtest
        - path: /
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 0.01
    mariadb:
      resources:
        requests:
          cpu: 0.01
    
