---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: prometheus
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: prometheus
    version: 9.1.0
  values:
    server:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        hosts: [ fluxtest ]
      resources:
        requests:
          cpu: 0.01
