---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: wordpress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: wordpress
    version: 7.1.0
  values:
    ingress:
      enabled: true
      hosts:
        - name: wp.fluxtest
        - path: /
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 0.01
    mariadb:
      resources:
        requests:
          cpu: 0.01
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: wordpress2
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: wordpress2
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: wordpress2
    version: 7.1.0
  values:
    ingress:
      enabled: true
      hosts:
        - name: wp2.fluxtest
        - path: /
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 0.01
    mariadb:
      resources:
        requests:
          cpu: 0.01
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: wordpress3
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: wordpress3
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: wordpress3
    version: 7.1.0
  values:
    ingress:
      enabled: true
      hosts:
        - name: wp3.fluxtest
        - path: /
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 0.01
    mariadb:
      resources:
        requests:
          cpu: 0.01
---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: wordpress4
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: wordpress4
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: wordpress4
    version: 7.1.0
  values:
    ingress:
      enabled: true
      hosts:
        - name: wp4.fluxtest
        - path: /
    service:
      type: ClusterIP
    resources:
      requests:
        cpu: 0.01
    mariadb:
      resources:
        requests:
          cpu: 0.01