---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~4.0
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: '"Halt updates for now"'
    flux.weave.works/locked_user: Stefan Prodan <stefan@weave.works>
spec:
  releaseName: redis
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: stable/wordpress
    #version: 5.1.3
  valueFileSecrets:
    # the redis-auth secret contains the password value
    #- name: redis-auth
  values:
