---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: demo
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~4.0
spec:
  releaseName: wordpress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: wordpress
    version: 7.1.0
  values:
    ingress:
      enabled: true
      hosts:
        - name: wp.fluxtest
        - path: /
    service:
      type: ClusterIP
    persistence:
      storageClass: microk8s-hostpath
    resources:
      requests:
        cpu: 0.01
    mariadb:
      persistence:
        storageClass: microk8s-hostpath
      resources:
        requests:
          cpu: 0.01
    
