---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: demo
spec:
  releaseName: redis
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: stable/wordpress
    version: 7.1.0
    #valueFileSecrets:
    # the redis-auth secret contains the password value
    #- name: redis-auth
    #values:
